#-------------------------------
# General Site Settings
title: Dreamsify
logo: site_images/logo/logo_blk_tagline.png 
logo_w: site_images/logo/logo_white_tagline.png
description: Dreamsify is a custom products marketplace producing orders on demand.


#-------------------------------
# intro Settings
# images wiil be fetched from the image/ folder
intro:
  say-hello: Couldn't find it <strong><a>Anywhere?</a></strong>
  bio:  'At Dreamsify we build upon <strong><a>your imagination</a></strong> to bring your ideas to life. We fabricate ideas proposed by you into <strong><a>premium products</a></strong> to make your life hassle-free and to transform your dreams into reality, delivered right at your doorstep.'
  slideshow:
    - img: intro/i1.png
      alt: 'library couch'
      title: From Household
      cap: ''
    - img: intro/i2.png
      alt: industrial jigs
      title: to Industrial
      cap: ''  
    - img: intro/i3.png
      alt: websites/apps
      title: to Software and so on...
      cap: ''


#-------------------------------
# Three Simple Steps
simplesteps_head: Where there's a will, there's <Strong><a href="#">Dreamsify!</a></strong>
simplesteps_subhead:  "Imagine beyond Existence"
simplesteps:
  - image: simple_steps/crow1.png
    alt: 'The Need of Dreamsify'
    title: <strong><a>Customize</a></strong> with us
    desc: We are the world's first and only company to solve problems in <strong><a>multiple domains</a></strong> by applying <strong><a>unconventional thinking</a></strong> to problems by embarking on a <strong><a>revolutionary path towards innovation.</a></strong>
  
  - image: simple_steps/crow2.png
    alt: 'The Ease of Dreamsify'
    title: No <strong><a>Boundaries</a></strong>
    desc: 'We deal with an endless range of products encompassing sectors like <strong><a>housing, industries, hotels, restaurants, technology and so on</a></strong>.'
  
  - image: simple_steps/crow3.png
    alt: 'The Benifits of Dreamsify'
    title: '<strong><a>Magic</a></strong> at your doorstep'
    desc: 'Order now in <strong><a>single or bulk quantities</a></strong> and be assured to have a hassle-free experience delivered at the comfort of your own home.'
  
#-------------------------------
# Team Details
our_team_heading: About Us
our_team_subtext: 'We are a team of highly trained professionals comprising of IITians and NIFTians. <br /> We ensure that you are provided with premium quality products while building loyalty across every touchpoint. We understand your hurdles and offer you the best, wisely curated solution chosen through methodical deliberation.'
team:
  - name: Prakhar Kumar
    pic: team_members/01.jpg
    position: co-founder and CEO
    social:
      - title: linkedin
        url: https://in.linkedin.com/in/prakhar-kumar-iitism
      - title: globe
        url: https://meetprakhar.github.io/
      - title: envelope-o
        url: 'mailto: pka.alld.97@gmail.com'

  - name: Anjali R. Pahal
    pic: team_members/02.jpg
    position: co-founder and CTO
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/anjali-rani
      - title: github
        url: https://github.com/asciarp08
      - title: envelope-o
        url: 'mailto: anjalirpahal08@gmail.com'

  - name: Preksha Agarwal
    pic: team_members/03.jpg
    position: co-founder and COO 
    social:
      - title: linkedin
        url: 'https://www.linkedin.com/in/preksha-agarwal-507764191'
      - title: instagram
        url: 'https://www.instagram.com/notanormiehere/?hl=en'
      - title: envelope-o
        url: 'mailto: preksha242@gmail.com'

  - name: Eric John Dungdung
    pic: team_members/04.jpg
    position: Marketing Head 
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/eric-john-dungdung-452b27158/
      - title: instagram
        url: https://www.instagram.com/pirate_hothead/?hl=en
      - title: envelope-o
        url: 'mailto: eric.17je002743@mech.iitism.ac.in'

#-------------------------------
# contact Us Settings
contactus:
  head: Let’s Talk Together
  intro: 'Shoot us an e-mail or give us a call. '
  contacts:
    - icon: map
      details: 'A-9 vinayak city square <br />
                7/9 S.P.Marg
                Civil lines <br />
                Prayagaraj'
    - icon: phone
      details: '+91-7367040374'
    - icon: envelope-open
      details: 'contact@dreamsify.com'

#-------------------------------
# WorkFlow Settings

workflow:
  intro: 'Personal Care to each Request'
  flow_end: work_flow/w5.png
  timelinedata:
    - img: work_flow/w1.png
      head1: 'Get in touch'
      head2: 
      subhead: 
      desc: 'Contact us with your problem, need or idea. One of our consultants will reach back to you. Get expert guidance to mould your idea into something real.'

    - img: work_flow/w2.png
      head1: 'Place the order'
      head2: 
      subhead: 
      desc: 'No need to wait anymore. <br />
      <div class="container text-center" style="padding-left: 0; padding-right: 0; margin-top: 20px; display: flex; justify-content: left; align-items: center;">     
          <a href="#OrderFormSection" class="btn-sm round-edge no-edge scroll_button" style="color:black; width: auto !important; padding: 10px 10px 10px 10px;">
            <span style="font-size: 20px;">    Order Now!    </span>
          </a>
      </div>
      '

    - img: work_flow/w3.png
      head1: 'This is where the Magic happens'
      head2: 
      subhead: 
      desc: 'Skilled craftsmen diligently work to build quality products.'

    - img: work_flow/w4.png
      head1: 'Hurray! Delivered at your doorstep.'
      head2: 
      subhead: 
      desc: 'Premium from Beginning to End.'

    - img: work_flow/w5.png
      head1: 'Feel Like a King!'
      head2: 
      subhead: 
      desc: "You have the only piece in the world. Your idea will never be used for anyone else, it's just yours to enjoy!"

#-------------------------------
# Footer Settings
# useful_links_cols can have value as 1 or 2

footer:
  logo_href: '#'
  desc: 'Company vision Here'
  contacts:
    - icon: map
      head: Find Us
      details: 'A-9 vinayak city square <br />
                7/9 S.P.Marg
                Civil lines <br />
                Prayagaraj'
    - icon: phone
      head: Call Us
      details: '+91-7367040374'
    - icon: envelope-open
      head: Mail Us
      details: 'contact@dreamsify.com'
  social:
      - icon: twitter twitter-bg
        url: 'https://twitter.com/DreamsifyO'
      - icon: facebook facebook-bg
        url: 'https://www.facebook.com/Dreamsifyofficial-102536301599757/'
      - icon: instagram instagram-bg
        url: 'https://www.instagram.com/dreamsify.official/'
      - icon: linkedin linkedin-bg
        url: 'https://www.linkedin.com/company/dreamsify'
        
  useful_links_cols: 1
  useful_links:
    - name: 'Home'
      link: '#'
    - name: 'Order'
      link: '#OrderFormSection'
    - name: 'Contact Us'
      link: contact-us
    - name: 'FAQs'
      link: faq
    - name: 'Blog'
      link: blog
    - name: 'Our Team'
      link: team
  subscribe_desc: 'Don’t miss to subscribe to our new feeds. Leave your e-mail below.'


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: dreamsify # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username



#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Form Settings
formhold: 
  address: Address
  company: "Your Company *"
  faq: "Question *"
  mail-id: "Your Email *"
  message: "What's on your mind?"
  message-order: "What is on your mind ? Eg: I want a coffee table with an aquarium built into it. *"
  name: "Your Name *"
  phone: "Phone Number *"
  phone_optional: "Phone Number"


#---------------------------------
# Mobile verification pattern
mob-pattern: \d{3}[\-]\d{3}[\-]\d{4}